import type { SeedMessage } from "./types";

/**
 * The demo mailbox. Deterministic on purpose: `buildEmails` fans these out into
 * a full window, so the same range always produces the same run.
 */
export const SEED_MESSAGES: readonly SeedMessage[] = [
  {
    category: "reply_needed",
    subject: "Re: Q3 pricing — can you confirm seats?",
    from: "Dana Whitfield · Northwind",
    snippet: "We need the final count before Friday so procurement can raise the PO.",
    reason: "direct question to you, unanswered for 2 days, thread has 4 replies",
    body: "Hi — procurement needs the seat count locked before Friday. Can you confirm 40 or 45? Happy to hop on a call if easier.",
  },
  {
    category: "reply_needed",
    subject: "Contract redlines back from legal",
    from: "Marcus Feld · Legal",
    snippet: "Two clauses flagged, otherwise clean. Sending the tracked copy now.",
    reason: "action requested, deadline language, sender in your frequent contacts",
    body: "Two clauses flagged (5.2 indemnity, 9.1 term). Everything else is clean — can you approve today?",
  },
  {
    category: "interview",
    subject: "Onsite loop — Staff Product Designer",
    from: "Talent @ Arcadia",
    snippet: "We would love to schedule your final loop for the week of the 12th.",
    reason: "recruiting domain + scheduling intent + role title in subject",
    body: "Congratulations on clearing the portfolio round. We would like to book your final loop: four sessions over one day.",
  },
  {
    category: "interview",
    subject: "Application received: Design Engineer",
    from: "careers@lumen.dev",
    snippet: "Thanks for applying. Our team reviews every portfolio within five days.",
    reason: "ATS auto-reply pattern, careers@ sender",
    body: "Thanks for applying to Lumen. We review every application within five business days.",
  },
  {
    category: "calendar",
    subject: "Invitation: Roadmap sync @ Thu 10:00",
    from: "calendar-notification",
    snippet: "Roadmap sync with Platform, 45 minutes, Meet link attached.",
    reason: "iCal attachment detected, RSVP required",
    body: "Roadmap sync — Platform + Design. Agenda in the doc, 45 minutes, Meet link below.",
  },
  {
    category: "calendar",
    subject: "Rescheduled: 1:1 with Priya",
    from: "Priya Raman",
    snippet: "Moving this to Wednesday so I can join from the office.",
    reason: "calendar update on an existing accepted event",
    body: "Shifting our 1:1 to Wednesday 15:00 — I will be in the office and can grab a room.",
  },
  {
    category: "finance",
    subject: "Statement ready — September",
    from: "Monzo Business",
    snippet: "Your monthly statement and category breakdown are available.",
    reason: "banking domain, statement cadence, no action requested",
    body: "Your September statement is ready. Spend is down 8% versus August, mostly software.",
  },
  {
    category: "finance",
    subject: "Payroll approved for the 28th",
    from: "Deel",
    snippet: "Two contractors added this cycle. Total run 14,280.00.",
    reason: "payroll provider, monetary totals, recurring cycle",
    body: "Payroll for this cycle is approved and will settle on the 28th. Two new contractors included.",
  },
  {
    category: "receipts",
    subject: "Your receipt from Figma",
    from: "billing@figma.com",
    snippet: "Invoice 4417-B for the Organization plan, paid with Visa ending 4021.",
    reason: "invoice number + payment confirmation template",
    body: "Payment received. Invoice 4417-B, Organization plan, 12 editors.",
  },
  {
    category: "receipts",
    subject: "Uber receipt — Tuesday trip",
    from: "receipts@uber",
    snippet: "Trip to Kings Cross, 18 minutes, charged to Amex ending 1042.",
    reason: "receipts@ sender with itemised total",
    body: "Thanks for riding. 18 minutes, 4.2 miles, charged to your Amex.",
  },
  {
    category: "newsletters",
    subject: "The Weekly Cadence — issue 214",
    from: "Cadence",
    snippet: "This week: how four teams rebuilt their design review ritual.",
    reason: "issue number, list-unsubscribe header present",
    body: "Issue 214 — four teams, four very different takes on design review.",
  },
  {
    category: "newsletters",
    subject: "Typesafe Research Digest",
    from: "research@typesafe",
    snippet: "JEV-2 evaluation notes, plus a walkthrough of the routing head.",
    reason: "periodical sender, no direct address, unsubscribe footer",
    body: "This month: JEV-2 evaluation notes and a short walkthrough of the routing head.",
  },
  {
    category: "social",
    subject: "Ana mentioned you in a comment",
    from: "notifications@figma",
    snippet: "Ana: \"@you does this cover the empty state?\" on Onboarding v4.",
    reason: "social notification, mention event, low urgency",
    body: "Ana mentioned you on frame Onboarding v4 — \"does this cover the empty state?\"",
  },
  {
    category: "social",
    subject: "You have 3 new connection requests",
    from: "LinkedIn",
    snippet: "Two recruiters and a former colleague want to connect.",
    reason: "network activity digest, no action required",
    body: "Three people want to connect with you this week.",
  },
  {
    category: "promotional",
    subject: "48 hours only — 40% off annual",
    from: "Offers @ Tallow",
    snippet: "Our biggest sale of the year ends Sunday at midnight.",
    reason: "urgency language + discount token + bulk sender",
    body: "Our biggest sale of the year. 40% off annual plans, ends Sunday.",
  },
  {
    category: "promotional",
    subject: "You left something behind",
    from: "shop@meridian",
    snippet: "Your cart is still waiting. Complete checkout and get free shipping.",
    reason: "abandoned-cart template, marketing ESP headers",
    body: "Still thinking it over? Your cart is saved, and shipping is on us today.",
  },
  {
    category: "spam",
    subject: "URGENT: your account will be suspended",
    from: "security-alert@mail-verify.co",
    snippet: "Verify your identity within 24 hours to avoid permanent closure.",
    reason: "display-name spoofing, mismatched reply-to, credential bait",
    body: "Immediate action required. Confirm your identity to prevent suspension.",
  },
  {
    category: "spam",
    subject: "Congratulations, you have been selected",
    from: "winner@promo-intl.net",
    snippet: "Claim your reward by confirming your banking details today.",
    reason: "lottery pattern, requests financial details, unknown domain",
    body: "You have been selected. Confirm your details to release the payment.",
  },
  {
    category: "reply_needed",
    subject: "Feedback on the triage spec?",
    from: "Sam Okonkwo",
    snippet: "Left comments in section 3 — mostly about the fallback path.",
    reason: "question mark in subject, colleague, awaiting your response",
    body: "Comments are in, mostly section 3. What do you want to do about the fallback path?",
  },
  {
    category: "interview",
    subject: "Take-home review scheduled",
    from: "people@northbeam",
    snippet: "Two of our engineers will walk through your submission on Thursday.",
    reason: "hiring pipeline stage language",
    body: "We have scheduled your take-home review for Thursday with two engineers.",
  },
  {
    category: "calendar",
    subject: "Accepted: Design critique",
    from: "Ivy Chen",
    snippet: "Ivy accepted your invitation for Tuesday at 14:30.",
    reason: "RSVP response to an event you organised",
    body: "Ivy Chen accepted your invitation.",
  },
  {
    category: "finance",
    subject: "Card ending 4021 — unusual spend",
    from: "Amex Alerts",
    snippet: "A 480.00 charge was flagged for review. Was this you?",
    reason: "financial institution alert, verification request from known sender",
    body: "We flagged a 480.00 charge at a new merchant. Confirm it was you.",
  },
  {
    category: "social",
    subject: "Tomas replied to your thread",
    from: "X",
    snippet: "Three replies and eleven likes since yesterday.",
    reason: "social platform digest",
    body: "Your post picked up 11 likes and 3 replies overnight.",
  },
  {
    category: "newsletters",
    subject: "Longform: the state of async work",
    from: "The Lattice",
    snippet: "A 12-minute read on distributed teams and meeting debt.",
    reason: "editorial newsletter, read-time marker",
    body: "This week, a 12-minute read on meeting debt and what replaced it.",
  },
  {
    category: "promotional",
    subject: "New arrivals, picked for you",
    from: "Halden Goods",
    snippet: "Autumn drop is live. Members get early access until Friday.",
    reason: "merchandising campaign, personalised-recommendation template",
    body: "The autumn drop is live, and members see it first.",
  },
  {
    category: "reply_needed",
    subject: "Intro: you ↔ Helena (advisor)",
    from: "Tomas Berg",
    snippet: "Making the connection I mentioned — Helena has run this play twice.",
    reason: "double opt-in intro, response expected by both parties",
    body: "Helena, meet the team building the triage tool. I will get out of the way.",
  },
  {
    category: "spam",
    subject: "Re: Re: invoice attached",
    from: "accounts@bluewave-ltd.biz",
    snippet: "Kindly find attached the outstanding invoice for immediate settlement.",
    reason: "forged reply chain, unexpected attachment, unknown counterparty",
    body: "Kindly settle the attached invoice at your earliest convenience.",
  },
  {
    category: "interview",
    subject: "Offer details — next steps",
    from: "Talent @ Arcadia",
    snippet: "Attaching the written offer and a summary of the equity grant.",
    reason: "offer-stage vocabulary from an active thread",
    body: "Delighted to share the written offer. Take your time, and let us know about the start date.",
  },
];
